In [17]:
import numpy as np

In [18]:
storm = np.load('/Users/rsahrae/PycharmProjects/PeaIsland_Hindcast/CASCADE/data/PeaIsland_init/Storms/storms_1992_2010_peaisland.npy')
storm

array([[0.000e+00, 2.437e-01, 1.171e-01, 9.760e+00, 3.600e+01],
       [0.000e+00, 2.427e-01, 9.580e-02, 1.271e+01, 3.600e+01],
       [0.000e+00, 2.141e-01, 9.120e-02, 1.175e+01, 3.600e+01],
       [0.000e+00, 1.829e-01, 8.110e-02, 9.770e+00, 6.000e+00],
       [0.000e+00, 1.727e-01, 7.720e-02, 1.004e+01, 1.600e+01],
       [1.000e+00, 2.544e-01, 7.690e-02, 1.271e+01, 2.900e+01],
       [1.000e+00, 2.099e-01, 1.141e-01, 1.040e+01, 3.600e+01],
       [1.000e+00, 2.069e-01, 1.061e-01, 1.060e+01, 3.600e+01],
       [1.000e+00, 1.988e-01, 3.600e-02, 1.357e+01, 1.400e+01],
       [1.000e+00, 1.901e-01, 1.211e-01, 1.031e+01, 3.600e+01],
       [2.000e+00, 2.616e-01, 9.240e-02, 1.091e+01, 3.600e+01],
       [2.000e+00, 2.171e-01, 7.320e-02, 1.235e+01, 3.600e+01],
       [2.000e+00, 2.020e-01, 7.050e-02, 1.145e+01, 2.900e+01],
       [2.000e+00, 1.807e-01, 7.320e-02, 1.016e+01, 2.800e+01],
       [2.000e+00, 1.757e-01, 5.920e-02, 1.246e+01, 3.600e+01],
       [3.000e+00, 2.474e-01, 8.480e-02,

In [14]:
storm = np.load('/Users/rsahrae/PycharmProjects/PeaIsland_Hindcast/CASCADE/data/PeaIsland_init/Storms/storms_1992_2010_new.npy')
storm

array([[ 0.        ,  3.        ,  2.3511193 ,  1.73173116, 13.328125  ,
         7.        ],
       [ 1.        ,  8.        ,  2.49252433,  1.72065825, 12.1171875 ,
         8.        ],
       [ 2.        ,  8.        ,  2.37657367,  1.84893077, 13.328125  ,
         7.        ],
       [ 3.        ,  8.        ,  2.41773869,  1.73730715, 13.328125  ,
         8.        ],
       [ 4.        , 12.        ,  4.03502995,  1.76236279, 17.7421875 ,
        21.        ],
       [ 5.        , 15.        ,  2.82001727,  1.75151147, 12.1171875 ,
         7.        ],
       [ 6.        , 16.        ,  2.28098319,  1.79893965, 13.328125  ,
         8.        ],
       [ 7.        , 18.        ,  2.18264694,  1.7059816 , 11.015625  ,
         7.        ],
       [ 8.        , 18.        ,  2.35032704,  1.8638541 , 12.1171875 ,
         7.        ],
       [ 9.        , 19.        ,  2.7261373 ,  1.7734725 , 16.125     ,
         9.        ],
       [10.        , 19.        ,  2.23341459,  1.

In [16]:
storm = np.load('/Users/rsahrae/PycharmProjects/PeaIsland_Hindcast/CASCADE/data/PeaIsland_init/Storms/1992_2010/storms_1992_2010.npy')
storm

array([[1.10000000e+01, 4.52192396e-01, 2.15272194e-01, 7.86826655e+00,
        1.66522000e+05]])

In [12]:
import numpy as np

storm_path = (
    "/Users/rsahrae/PycharmProjects/PeaIsland_Hindcast/CASCADE/"
    "data/PeaIsland_init/Storms/storms_1992_2010.npy"
)

# Load storm file
storm = np.load(storm_path)

print("Before:")
print(storm[:10])

# CASCADE storm columns:
# 0 = time/year index
# 1 = Rhigh
# 2 = Rlow
# 3 = Period
# 4 = duration

storm[:, 1] = storm[:, 1] * 10   # Rhigh
storm[:, 2] = storm[:, 2] * 10   # Rlow

print("\nAfter multiplying Rhigh and Rlow by 10:")
print(storm[:10])

# Save as a NEW file so you do not overwrite the original
out_path = (
    "/Users/rsahrae/PycharmProjects/PeaIsland_Hindcast/CASCADE/"
    "data/PeaIsland_init/Storms/storms_1992_2010_Rhigh_Rlow_x10.npy"
)

np.save(out_path, storm)

print(f"\nSaved multiplied storm file to:\n{out_path}")

Before:
[[0.00000000e+00 1.93084192e-01 9.53247200e-02 1.15929129e+01
  2.70000000e+01]
 [0.00000000e+00 2.22020790e-01 1.21347655e-01 1.03630515e+01
  1.60000000e+01]
 [0.00000000e+00 2.17616674e-01 1.00731675e-01 1.32184456e+01
  7.60000000e+01]
 [1.00000000e+00 1.93495871e-01 1.17314294e-01 1.05530134e+01
  2.70000000e+01]
 [2.00000000e+00 2.32685994e-01 9.80793938e-02 1.20055147e+01
  1.60000000e+01]
 [2.00000000e+00 1.92469062e-01 7.80285360e-02 1.25183824e+01
  1.60000000e+01]
 [3.00000000e+00 2.19584774e-01 9.02566802e-02 1.37212612e+01
  2.70000000e+01]
 [3.00000000e+00 1.79397066e-01 6.69446525e-02 1.47016602e+01
  1.50000000e+01]
 [4.00000000e+00 2.23608253e-01 8.12082186e-02 1.54533155e+01
  4.00000000e+01]
 [4.00000000e+00 1.86067205e-01 1.06362926e-01 1.11827567e+01
  2.70000000e+01]]

After multiplying Rhigh and Rlow by 10:
[[ 0.          1.93084192  0.9532472  11.59291295 27.        ]
 [ 0.          2.2202079   1.21347655 10.36305147 16.        ]
 [ 0.          2.1761667

In [ ]:
import pandas as pd

df = pd.read_csv('/Users/rsahrae/PycharmProjects/PeaIsland_Hindcast/CASCADE/data/PeaIsland_init/Storms/cascade_storms.csv')


df

In [ ]:
import json
with open('/Users/rsahrae/PycharmProjects/PeaIsland_Hindcast/CASCADE/scripts/input_preperation/CoastSat/CASCADE_Domain.json', 'r') as f:
    data = json.load(f)
print(data)

In [ ]:
with open('/Users/rsahrae/PycharmProjects/PeaIsland_Hindcast/CASCADE/scripts/input_preperation/CoastSat/HAT_domains.json', 'r') as f:
    data = json.load(f)
print(data)

In [ ]:
storm_97_2019 = np.load("/Users/rsahrae/PycharmProjects/PeaIsland_Hindcast/CASCADE/data/PeaIsland_init/Storms/storms_1997_2019.npy")

In [ ]:
storm_97_2019

In [ ]:
import os
import re

directory_path = "/Users/rsahrae/PycharmProjects/PeaIsland_Hindcast/CASCADE/data/1996"

for filename in os.listdir(directory_path):
    match = re.search(r'resample_domain_(\d+)_1996', filename)
    if match:
        index = int(match.group(1))
        if 80 <= index <= 121:
            old_path = os.path.join(directory_path, filename)
            new_filename = f"resampled_domain_{index}_1996.npy"
            new_path = os.path.join(directory_path, new_filename)

            os.rename(old_path, new_path)
            print(f"Renamed '{filename}' → '{new_filename}'")


In [ ]:
import numpy as np

# 1. Load CSV data into an array
# delimiter specifies the separator (usually ',')
# skip_header skips the first row if it contains column titles
data = np.genfromtxt('/Users/rsahrae/PycharmProjects/PeaIsland_Hindcast/CASCADE/data/PeaIsland_init/Storms/cascade_storms.csv', delimiter=',', skip_header=1)

# 2. Save the array as a .npy file
np.save('storms_1992_2010.npy', data)
